GET http://localhost:8888/api/user 

###

POST http://localhost:8888/api/user HTTP/1.1
Content-Type: "application/json"

{
    "id" : 1 ,
    "name" : "product testing" ,
    "price"  : 100
}

###

PUT http://localhost:8888/api/user/3 
Content-Type: "application/json"

{
    "id" : 2 ,
    "name" : "product testing 2" ,
    "price"  : 200 
}

###

DELETE http://localhost:8888/api/user/2 HTTP/1.1
