GET http://localhost:8888/api/user 

###

POST http://localhost:8888/api/user/register HTTP/1.1
Content-Type: "application/json"

{
    "firstName" : "sorasak" ,
    "lastName" : "siangchin" ,
    "email" : "sorasak@gmail.com" ,
    "password" : "123456" ,
    "age" : "23" 
}

###

POST http://localhost:8888/api/user/login HTTP/1.1
Content-Type: "application/json"

{
    "email" : "sorasak@gmail.com" ,
    "password" : "123456" 
}
